language: scala

scala:
   - 2.12.12

jdk:
   - oraclejdk11

matrix:
  include:
  - os: linux
    dist: focal
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        # packages:
        # - g++-5
    # env:
    # - MATRIX_EVAL="CC=gcc-5.5 && CXX=g++-5.5"

# before_install:
#  - eval "${MATRIX_EVAL}"

script:
  - sbt sbt -Dheap=4096m -Dgpu=false -DpackagedTF=true -J-XX:MaxDirectMemorySize=2gclean coverage test coverageReport && sbt coverageAggregate
after_success:
  - sbt coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/45cb5820ca70c8a3445e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
